djeedai/bevy_tweening

src/lens.rs

Add more predefined rotation lenses interpolating the angle of rotation
instead of the `Quat` itself directly. Document at the `lens` module
level the difference between the shortest-path lens and the
angle-focused ones.
Bug: #5

Add and document various rotation lenses

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
src/lens.rs
src/lib.rs
src/plugin.rs

Enable minimal dependencies with new features `bevu_sprite` and
`bevy_ui`, removing the `bevy/render` mandatory dependency. Those new
features are enabled by default, and enable the built-in lenses for the
related Bevy crates. The core `bevy_tweening` crate itself does not take
any optional Bevy dependency anymore, allowing for a slim build with
only the core Bevy functionalities.

Tighter dependencies with features

---

src/lib.rs

Change the example in the `lib.rs` module documentation to not rely on
the `bevy_sprite` feature, to allow building cleanly with the
`--no-default-features` flag. Replace the use of `SpriteBundle` with
`TransformBundle`, which is not behind a feature flag so is alway
available.

Fix `lib.rs` doc to not rely on feature

---

Cargo.toml
examples/colormaterial_color.rs
examples/menu.rs
examples/sequence.rs
examples/sprite_color.rs
examples/text_color.rs
examples/transform_rotation.rs
examples/transform_translation.rs
examples/ui_position.rs

Upgrade the version of `bevy-inspector-egui` to `0.10` for Bevy v0.7
compatibility, otherwise the examples were building with Bevy v0.6. Fix
the examples which now build correctly with Bevy v0.7.

Upgrade `bevy-inspector-egui` and fix examples

---

CHANGELOG.md
src/lib.rs
src/tweenable.rs

Allow a `Tween` to play backward by setting its direction with
`Tween::set_direction()`.

Add `Tween::set_direction()` for backward playback

---

src/tweenable.rs

Old:
1s 320ms
Left:  140292640
Right: 140292630
New:
759ms
Success

Fix loss of precision in AnimClock and improve performance

---

CHANGELOG.md
Cargo.toml
examples/sequence.rs
src/lib.rs
src/tweenable.rs

Current paint points:
- All tweenables in sequences and tracks are allocated even though most people will primarily use the built-ins.
- There's double boxing causing extreme indirection: tweenables are stored in a vec which contains boxes of boxes (since `IntoBoxDynTweenable` unconditionally boxes and there's no way to avoid this without specialization which is a long ways away).
- Creating seqs/tracks of heterogeneous types is very ugly and confusing.
Solutions:
- Use an enum to fake dynamic typing for built-ins.
- Provide an impl for boxed types for 3P tweenables.
- Export a BoxedTweenable type to alleviate typing pain.
This makes built-ins zero cost while 3P types only suffer one layer of indirection.
Closes #28

Optimize out allocations as much as possible

---

CHANGELOG.md
examples/colormaterial_color.rs
examples/menu.rs
examples/sequence.rs
examples/sprite_color.rs
examples/text_color.rs
examples/transform_rotation.rs
examples/transform_translation.rs
examples/ui_position.rs
src/lib.rs
src/tweenable.rs

Fixes #17
This supports an animation like the following:
```rust
pub fn error_shake(current: &Transform) -> Sequence<Transform> {
let wiggle = Quat::from_rotation_z(PI / 16.);
Tween::new(
EaseMethod::Linear,
TweeningType::Once,
Duration::from_millis(25),
TransformRotationLens {
start: current.rotation,
end: current.rotation * wiggle.inverse(),
},
)
.then(Tween::new(
EaseMethod::Linear,
TweeningType::PingPongTimes(3),
Duration::from_millis(50),
TransformRotationLens {
start: current.rotation * wiggle.inverse(),
end: current.rotation * wiggle,
},
))
.then(Tween::new(
EaseMethod::Linear,
TweeningType::Once,
Duration::from_millis(25),
TransformRotationLens {
start: current.rotation * wiggle,
end: current.rotation,
},
))
}
```

Support running an animation N times

---

src/tweenable.rs

Carry time delta between tweens in a Sequence

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
README.md
benchmarks/Cargo.toml
benchmarks/benches/lens.rs
examples/colormaterial_color.rs
examples/menu.rs
examples/sequence.rs
examples/sprite_color.rs
examples/text_color.rs
examples/transform_rotation.rs
examples/transform_translation.rs
examples/ui_position.rs
src/lens.rs
src/lib.rs
src/plugin.rs
src/tweenable.rs

Upgrade to the latest released version 0.8.0 of Bevy.
Add a new `bevy_asset` feature to enable animation of Bevy assets
(types implementing the `Asset` trait). Bevy 0.8 does not contain
`bevy_asset` in its defaul features, so this new feature reflects that
new possibility to build Bevy and 🍃 Bevy Tweening without support
for the `bevy_asset` crate. The new feature is enabled by default for
discoverability and to prevent a behavior breaking change.

Upgrade to Bevy 0.8

---

CHANGELOG.md
examples/sequence.rs
src/lens.rs
src/lib.rs
src/plugin.rs

Perhaps I'm missing something, but I don't see a use case for having an Animator that doesn't have a tween and therefore does nothing. Getting rid of this option makes the animator API surface significantly simpler.

Get rid of Optional tween

---

CHANGELOG.md
examples/menu.rs
src/tweenable.rs

Make `Delay::new()` panic if a zero duration is passed as argument. Fix the `menu` example to skip inserting a `Sequence<Transform>` containing a zero-duration `Delay`.
Bug: #41

Forbid `Delay` with a zero duration

---

CHANGELOG.md
src/tweenable.rs

Fix the repeat mode being broken after the first iteration due to
`AnimClock::progress()` reporting a progress greater than `1.`, which was
breaking the logic of `Tween` and `Lens`.
Also fix `Tween::rewind()` not restoring the original tween direction when
using a repeat strategy of `RepeatStrategy::MirroredRepeat`.
Fixes #42

Fix repeat mode broken after first iteration

---

examples/colormaterial_color.rs
examples/menu.rs
examples/sequence.rs
examples/sprite_color.rs
examples/text_color.rs
examples/transform_rotation.rs
examples/transform_translation.rs
examples/ui_position.rs

Make it easy to exit an example with the ESC key by adding the built-in
`bevy::window::close_on_esc()` system to all examples.

Add `close_on_esc()` system to all examples

---

CHANGELOG.md
src/lib.rs
src/plugin.rs

Fix the animator speed applying, which got broken as part of the refactor of #44.
Add a `speed()` getter to both `Animator<T>` and `AssetAnimator<T>`.
Add some simple test for speed, but this is not enough to make sure the feature doesn't regress, so logged #62 to follow-up with a proper regression test.
Fixes #61

Fix animator speed feature

---

examples/menu.rs
src/lib.rs
src/test_utils.rs
src/tweenable.rs

Clarify testing code and potential assertions message with the use of a new `assert_approx_eq!()` macro for `f32` equality check with a tolerance. The macro leverages `abs_diff_eq()` but produces a better assertion message in case of failure. It also allows skipping the tolerance parameter to use the default of `1e-5`, which is the "standard" tolerance to use for progress and other small-ish values that are expected to be equal but might be slightly off due to rounding errors.
This change ignores the complications of testing for floating-point equality in a generic way, which is too complex, and instead restrict the usage to values like progress (range [0:1]) and other small position values around the origin.

Add `assert_approx_eq!()` testing macro

---

CHANGELOG.md
src/tweenable.rs

Add two new methods to the `Tweenable<T>` trait:
- `set_elapsed(Duration)` sets the elapsed time of the tweenable. This is equivalent to `set_progress(duration().mul_f32(progress))`, with the added benefit of avoiding floating-point conversions and potential rounding errors resulting from it. `set_progress()` is now largely implemented in terms of and as a convenience wrapper to calling `set_elapsed()`.
- `elapsed()` which queries the elapsed time of the tweenable. This is equivalent to `duration().mul_f32(progress())`, again with better precision.
The elapsed API is the recommended way going forward to manipulate a tweenable's time outside of the normal `tick()` flow. It supersedes the progress API.
This change purposedly skips any discussion about what happens to completion events when …

Add elapsed API

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
README.md
src/lens.rs

Add a new `bevy_text` feature for more granular control over `Text`-related lenses, and change the `TextColorLens` to require that new feature instead of `bevy_ui`, as texts _can_ be used without the Bevy UI crate.
Fixes #68

Move `TextColorLens` under a new `bevy_text` feat.

---

CHANGELOG.md
src/lib.rs
src/plugin.rs
src/tweenable.rs

Ensure change detection on components and assets is only triggered when an animator effectively modifies said component or asset, and not invariably just by the simple fact of the animator ticking each frame.
This change modifies the signature of the `component_animator_system()` and `asset_animator_system()` public functions to directly consume a `ResMut<Events<TweenCompleted>>` instead of an
`EventWriter<TweenCompleted>`, to work around some internal limitations.
It also publicly exposes a new `Targetable` trait used to work around the impossibility to retrieve a `Mut<T>` from a `Mut<Assets<T>>`. Instead, the trait provides an "target dereferencing" method `target_mut()` which dereferences the target component or asset, and triggers its change detection. The trait is implemented for all …

Fix incorrect change detection triggering

---

src/plugin.rs

Fix registration of the `component_animator_system::<Text>` in the `TweeningPlugin` to depend on the new `bevy_text` feature, and not on the `bevy_ui` one.

Fix `bevy_text` plugin registration

---

CHANGELOG.md
src/lib.rs
src/plugin.rs
src/tweenable.rs

Change `Delay` into `Delay<T>`, and add support for raising a completion event or callback.
Bug: #69

Add completion event/callback on `Delay<T>`

---

CHANGELOG.md
src/lib.rs
src/tweenable.rs

Change the signature of `Tween::with_repeat_count()` to take an `impl Into<RepeatCount>` instead of a `RepeatCount` value, to make it easier to configure the `Tween`.
Implement for `RepeatCount`:
- `From<u32>` for an actual count, yielding `RepeatCount::Finite(value)`
- `From<Duration>` for a duration "count", yielding `RepeatCount::For(value)`

Take `impl Into<RepeatCount>` for easier usage

---

README.md
src/lib.rs
src/plugin.rs

Clarify the documentation around animation systems, which ones are added automatically by the `TweeningPlugin` and which ones need to be added manually, depending on which feature is active.
- Expand the Setup section of the README to explain the systems need to be added manually for most components and assets, and give a table for built-in ones where the system is automatically added.
- Add a similar section to the rustdoc section of `lib.rs`.
Also fix a couple of doc links.
Bug: #103

Clarify doc around systems

---

CHANGELOG.md
README.md
src/lens.rs
src/plugin.rs

I's pretty common to need the ability to fade UI elements/images on and off, so I added a lens for BackgroundColor. 
Simply tween the alpha value for two Color::rgb().set_a()
```rust
let selected_color = Color::RED;
let tween_opac = Tween::new(
EaseFunction::QuadraticIn,
Duration::from_secs(1),
UiBackgroundColorLens {
start: selected_color.set_a(0.9),
end: selected_color.set_a(0.0),
},
);
let animator = Animator::new(tween_opac);
```
It's very nice for flashing something on screen and removing after a delay, like a killfeed notification.
```rust
let selected_color = Color::RED;
let tween_opac_in = Tween::new(
EaseFunction::QuadraticIn,
Duration::from_millis(500),
UiBackgroundColorLens {
start: selected_color.set_a(0.0),
end: selected_color.set_a(0.9),
},
);
let tween_opac_out = …
```

BackgroundColor support

---

CHANGELOG.md
src/lens.rs

Hi. The `TextColorLens` can panic if the text section it's looking for isn't there. I just got it to do nothing in that case instead.

Fixed a panic in text color lens

---

CHANGELOG.md
examples/colormaterial_color.rs
src/lens.rs
src/lib.rs
src/plugin.rs

Change asset animation to behave like component animation, and retrieve the `Handle<T>` component referencing the asset to animate directly from a Bevy query on the same `Entity` instead of specifying it manually in the `AssetAnimator` itself.
Task: #101

Asset animator uses `Handle<T>` on same entity

---

Cargo.toml
README.md
benchmarks/Cargo.toml
src/lib.rs
src/plugin.rs
src/tweenable.rs

I've taken the liberty to bump the crate's own version to 0.9. The compatibility table in the README is also updated.

Upgrade to Bevy 0.12

---

README.md

I haven't had the chance to test the examples after these changes, other than making sure there are no type errors.
If you want me to I can do that tomorrow

Update README.md: Fix typos + types in examples

---

CHANGELOG.md
src/lens.rs
src/lib.rs
src/plugin.rs
src/tweenable.rs

Add the ability for all `Lens`es to avoid triggering change detection if they don't make any actual change to their target (component or asset).
This change modifies the signature of `Lerp::lerp()` to take `&mut dyn Targetable<T>` instead of `&mut T`. The `Targetable<T>` acts as a `Mut<T>`, marking the target as changed only if actually dereferenced mutably.
Note that we cannot use `Mut<T>` directly because we can't obtain a `Mut<A: Asset>` without marking the asset as mutable; see bevyengine/bevy#13104.
Fixes #91

Enable lenses to avoid change detection

---

src/plugin.rs
src/tweenable.rs

This PR adds with_completed_system() and other related methods to allow the user to run a one-shot system when an animation or delay completes. 
The main reason why I wanted to add this is to avoid polling for a single non-repeating event; using one-shot systems can be cleaner sometimes. But there are other use-cases like chaining actions or even other animations that cant be chained normally due to limitations in the library. In those cases you may think to use callbacks, but they don't allow you to easily interact with the world, which makes one-shot systems a necessity.

Run a one-shot system upon completion of Tween or Delay

---

Cargo.toml
README.md

The `EaseFunction` definition depends on the `bevy_math/curve` feature, which is unfortunately not re-exposed by Bevy. As a workaround, to make sure that feature is always active (since `EaseFunction` is a core type of `bevy_tweening`), we force a dependency on `bevy_color`, which itself already forces that feature. This is not ideal and brittle, but good enough until Bevy provides a better way.

Force `bevy_math/curve` feature through `bevy_color`

---

src/tweenable.rs

This PR is very simple: trigger observers when the TweenCompleted event gets sent out. I added this right next to event.send() so it will always happen if use "with_completed_event".
However, we may want to add an equivalent to "with_completed_event" so its opt-in, i.e. "with_completed_trigger" and "with_completed_trigger_targets".
For now, this is the easiest solution to get the ball rolling on this.

Trigger observers when TweenCompleted event is sent

---

src/lens.rs

Val::Vw, Val::Vh, Val::VMin, and Val::VMax were missing from the lerp_val function.

Added lerping for all variants of Val

---

src/lib.rs
src/plugin.rs

This adds an optional property to `Animator` that stores an entity.
If the property contains a value, it will be used as the target of the animation. Otherwise, the `Animator`'s entity will be used (default behavior).
This makes the creation of complex, modular tweens much easier. For example, you can now have one animator entity tweening `Transform::translation` and the other tweening `Transform::rotation`. Previously, this would have to be done with a single animator, which is very inflexible.
They can be used like this:
```rust
let sprite = commands.spawn(
SpriteBundle {
sprite: Sprite {
color: Color::RED,
custom_size: Some(Vec2::new(size, size)),
..default()
},
..default()
},
).id();
// This animator will animate the previously spawned entity …
```

Allow `Animator` to target other entities

---

Cargo.toml
benchmarks/Cargo.toml
benchmarks/benches/lens.rs
examples/menu.rs
examples/sequence.rs
examples/transform_rotation.rs
examples/transform_translation.rs
examples/ui_position.rs
examples/utils/mod.rs
src/lens.rs
src/lib.rs
src/plugin.rs
src/tweenable.rs

Easy upgrade, currently pointing at my branches for bevy_egui and bevy_inspector_egui.
Two Notes:
- Had to add bevy/bevy_picking to examples requirements, while bevy_egui doesn't use picking directly, get a runtime error without it
```Encountered an error in system `bevy_egui::capture_pointer_input_system`: SystemParamValidationError { skipped: false }```
- 0.16 added "std" and "libm" that switches out the math lib and transforms, we need those, should all bevy addons add features to reflect this?

update to bevy 0.16-rc
